services:
  - type: web
    name: yamaha-bot-1
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9

      # WASENDER API
      - key: WASENDER_API_KEY
        sync: false
      - key: WASENDER_BASE_URL
        value: https://www.wasenderapi.com/api

      # URL DO BOT
      - key: BASE_URL
        value: https://yamaha-bot-1.onrender.com

      # BANCO
      - key: DATABASE_URL
        value: sqlite:///yamaha.db

      # INATIVIDADE
      - key: TEMPO_INATIVIDADE
        value: 600